### ISSUE TITLE
detect data from pre-existing DOM elements

### ISSUE THREAD

**Issue by wheelerlaw** [d3plus/d3plus-text#105] opened 2019-03-18 21:37 UTC
The API for `textwrap` was far simpler in the previous iteration of d3plus, as it worked with existing elements whose dimensions were already defined. d3plus 2.0 adds unneeded complexity for wrapping text, and it does not seem to work with existing text elements. 

This was how simple it was to wrap text using d3plus:
```js
d3plus.textwrap()
    .container(d3.select("#rectWrap"))
    .draw();
```

Given how already difficult text wrapping in SVG is, the departure from an API that is as simple as that seems like the wrong direction. 

I'm requesting that the old but simpler API be ported into d3plus 2.0.

**Comment by davelandry** [comment] 2019-03-19 14:11
@wheelerlaw I agree, the old 1.0 logic of detecting the size, positioning, and text of a label based on the DOM structure was super handy. I don't have the capacity right now to port it over, but ideally the logic would be:

If the data passed to `textWrap` is an `HTMLELement` or `D3Selection`:
1. Analyze the shape to determine the `width`, `height`, `x`, and `y` properties
2. Analyze any available sibling `<text>` element to determine the `text` and any inline font styles

The old logic for parsing the size can be found [here](https://github.com/alexandersimoes/d3plus/blob/master/src/textwrap/helpers/parseSize.coffee), and the old logic for text is [here](https://github.com/alexandersimoes/d3plus/blob/master/src/textwrap/helpers/parseText.coffee). These are both used [here](https://github.com/alexandersimoes/d3plus/blob/master/src/textwrap/textwrap.coffee#L16-L21). The old code is in coffeescript 😒 

Consider these either notes for my future self, or guidance for someone to make a PR 🍻

**Comment by wheelerlaw** [comment] 2019-03-19 17:36
Super! If I have some spare cycles, I could take a stab at it. Perhaps this weekend.

**Comment by davelandry** [comment] 2019-05-14 13:57
duplicate of #6

**Closed as completed by davelandry** 2019-05-14 13:57 UTC
Labels: feature
